[package]
name = "LSB"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.20"
image = "0.25.4"
reqwest = { version = "0.12.9", features = ["blocking"]}
windows = { version = "0.58.0", features = ["Win32", "Win32_UI", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"]}